name: Terraform

on: [push]
env: 
   AWS_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets. SECRET_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up terrraform
        uses: hashicorp/setup-terraform@v3
        with:
          terrraform_version: 1.1.9
      - name: terrraform initialization
        uses: terraform init
      - name: validation
        uses: terraform validate
      - name: terraform format
        uses:  terraform fmt
      - name: terraform plan
        uses: terraform plan        

